-- Shared, server-settled Arena rounds for the ZenoWallet mini-app.
-- Run this once after supabase/schema.sql in the Supabase SQL editor.

create table if not exists public.arena_bot_profiles (
  id integer primary key,
  display_name text not null,
  avatar text not null,
  bankroll bigint not null default 10000 check (bankroll >= 0),
  active boolean not null default true
);

insert into public.arena_bot_profiles (id, display_name, avatar)
values
  (1, 'Искра', 'И'),
  (2, 'Молния', 'М'),
  (3, 'Кобальт', 'К'),
  (4, 'Лиса', 'Л'),
  (5, 'Титан', 'Т'),
  (6, 'Спектр', 'С')
on conflict (id) do nothing;

create table if not exists public.arena_rounds (
  id bigint generated by default as identity primary key,
  status text not null default 'open'
    check (status in ('open', 'finished')),
  created_at timestamptz not null default now(),
  closes_at timestamptz not null,
  finished_at timestamptz,
  total_pot bigint not null default 0 check (total_pot >= 0),
  winner_entry_id bigint,
  payout bigint not null default 0 check (payout >= 0)
);

create unique index if not exists arena_one_open_round_idx
  on public.arena_rounds (status)
  where status = 'open';

create index if not exists arena_rounds_history_idx
  on public.arena_rounds (id desc)
  where status = 'finished';

create table if not exists public.arena_entries (
  id bigint generated by default as identity primary key,
  round_id bigint not null references public.arena_rounds (id) on delete cascade,
  user_id bigint,
  bot_id integer references public.arena_bot_profiles (id),
  display_name text not null,
  avatar text not null,
  is_bot boolean not null default false,
  stake bigint not null check (stake > 0),
  payout bigint not null default 0 check (payout >= 0),
  is_winner boolean not null default false,
  created_at timestamptz not null default now(),
  constraint arena_entries_identity_check check (
    (is_bot and user_id is null and bot_id is not null)
    or (not is_bot and user_id is not null and bot_id is null)
  ),
  unique (round_id, user_id),
  unique (round_id, bot_id)
);

create index if not exists arena_entries_round_idx
  on public.arena_entries (round_id, id);

create or replace function public.arena_resolve_round(p_round_id bigint)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_round public.arena_rounds%rowtype;
  v_winner public.arena_entries%rowtype;
  v_pool bigint;
  v_roll numeric;
  v_payout bigint;
  v_users_state jsonb;
  v_user_state jsonb;
  v_user_key text;
  v_current_zeno bigint;
  v_next_zeno bigint;
begin
  select *
    into v_round
    from public.arena_rounds
   where id = p_round_id
   for update;

  if not found or v_round.status <> 'open' then
    return;
  end if;
  if v_round.closes_at > clock_timestamp() then
    raise exception 'Приём ставок ещё открыт';
  end if;

  select coalesce(sum(stake), 0)
    into v_pool
    from public.arena_entries
   where round_id = v_round.id;

  if v_pool <= 0 then
    raise exception 'В раунде нет участников';
  end if;

  v_roll := random() * v_pool;

  select candidate.*
    into v_winner
    from (
      select entry.*,
             sum(entry.stake) over (order by entry.id) as running_stake
        from public.arena_entries as entry
       where entry.round_id = v_round.id
    ) as candidate
   where v_roll < candidate.running_stake
   order by candidate.id
   limit 1;

  if not found then
    raise exception 'Не удалось определить победителя арены';
  end if;

  v_payout := floor(v_pool * 0.90)::bigint;

  update public.arena_entries
     set is_winner = (id = v_winner.id),
         payout = case when id = v_winner.id then v_payout else 0 end
   where round_id = v_round.id;

  if v_winner.is_bot then
    update public.arena_bot_profiles
       set bankroll = bankroll + v_payout
     where id = v_winner.bot_id;
  else
    select state_value
      into v_users_state
      from public.bot_state
     where state_key = 'users'
     for update;

    if not found or v_users_state is null
       or jsonb_typeof(v_users_state) <> 'object' then
      raise exception 'Supabase bot_state row state_key=users was not found or is invalid';
    end if;

    v_user_key := v_winner.user_id::text;
    v_user_state := coalesce(v_users_state -> v_user_key, '{}'::jsonb);
    if coalesce(v_user_state ->> 'zenotoken', '') ~ '^[0-9]+$' then
      v_current_zeno := (v_user_state ->> 'zenotoken')::bigint;
    else
      v_current_zeno := 0;
    end if;
    v_next_zeno := v_current_zeno + v_payout;
    v_users_state := jsonb_set(
      v_users_state,
      array[v_user_key, 'zenotoken']::text[],
      to_jsonb(v_next_zeno),
      true
    );
    update public.bot_state
       set state_value = v_users_state
     where state_key = 'users';

    update public.wallet
       set zeno_balance = v_next_zeno,
           updated_at = now()
     where user_id = v_winner.user_id;
  end if;

  update public.arena_rounds
     set status = 'finished',
         finished_at = clock_timestamp(),
         total_pot = v_pool,
         winner_entry_id = v_winner.id,
         payout = v_payout
   where id = v_round.id;
end;
$$;

create or replace function public.arena_get_state(
  p_user_id bigint,
  p_display_name text default 'Игрок'
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_round public.arena_rounds%rowtype;
  v_bot record;
  v_bot_count integer;
  v_stake bigint;
  v_pool bigint := 0;
  v_roll_index integer;
  v_round_id bigint;
  v_has_round boolean := false;
  v_participants jsonb := '[]'::jsonb;
  v_my_entry jsonb := null;
  v_winner jsonb := null;
  v_history jsonb := '[]'::jsonb;
begin
  if p_user_id is null or p_user_id <= 0 then
    raise exception 'Некорректный пользователь';
  end if;

  perform pg_advisory_xact_lock(816184092026);

  select *
    into v_round
    from public.arena_rounds
   where status = 'open'
   order by id desc
   limit 1
   for update;

  v_has_round := found;
  if v_has_round then
    v_round_id := v_round.id;
    if v_round.closes_at <= clock_timestamp() then
      perform public.arena_resolve_round(v_round.id);
      select *
        into v_round
        from public.arena_rounds
       where id = v_round_id;
      v_has_round := found;
    end if;
  else
    select *
      into v_round
      from public.arena_rounds
     order by id desc
     limit 1
     for update;
    v_has_round := found;
  end if;

  if v_has_round
     and v_round.status = 'open'
     and clock_timestamp() >= v_round.created_at
       + make_interval(
           secs => (2 + mod(abs(hashtext(v_round.id::text)::bigint), 7000) / 1000.0)::double precision
         )
     and not exists (
       select 1
         from public.arena_entries
        where round_id = v_round.id
          and is_bot
     ) then
    v_bot_count := 3 + floor(random() * 3)::integer;

    for v_bot in
      select id, display_name, avatar, bankroll
        from public.arena_bot_profiles
       where active and bankroll >= 25
       order by random()
       limit v_bot_count
       for update
    loop
      v_roll_index := 1 + floor(random() * 6)::integer;
      v_stake := (array[1, 2, 3, 5, 10, 15]::bigint[])[v_roll_index];
      v_stake := least(v_stake, v_bot.bankroll);

      update public.arena_bot_profiles
         set bankroll = bankroll - v_stake
       where id = v_bot.id;

      insert into public.arena_entries (
        round_id, bot_id, display_name, avatar, is_bot, stake
      )
      values (
        v_round.id, v_bot.id, v_bot.display_name, v_bot.avatar, true, v_stake
      );
      v_pool := v_pool + v_stake;
    end loop;

    if v_pool > 0 then
      update public.arena_rounds
         set total_pot = total_pot + v_pool
       where id = v_round.id;
    end if;

    select *
      into v_round
      from public.arena_rounds
     where id = v_round.id;
  end if;

  if v_has_round then
    select coalesce(
             jsonb_agg(
               jsonb_build_object(
                 'id', entry.id,
                 'name', entry.display_name,
                 'avatar', entry.avatar,
                 'isBot', entry.is_bot,
                 'bet', entry.stake,
                 'chance', case
                   when v_round.total_pot > 0
                     then round(entry.stake::numeric * 100 / v_round.total_pot, 1)
                   else 0
                 end,
                 'isMe', (not entry.is_bot and entry.user_id = p_user_id),
                 'isWinner', entry.is_winner,
                 'payout', entry.payout
               )
               order by entry.created_at, entry.id
             ),
             '[]'::jsonb
           )
      into v_participants
      from public.arena_entries as entry
     where entry.round_id = v_round.id;

    select jsonb_build_object(
             'id', entry.id,
             'name', entry.display_name,
             'avatar', entry.avatar,
             'bet', entry.stake,
             'chance', case
               when v_round.total_pot > 0
                 then round(entry.stake::numeric * 100 / v_round.total_pot, 1)
               else 0
             end,
             'isWinner', entry.is_winner,
             'payout', entry.payout
           )
      into v_my_entry
      from public.arena_entries as entry
     where entry.round_id = v_round.id
       and not entry.is_bot
       and entry.user_id = p_user_id;

    if v_round.status = 'finished' then
      select jsonb_build_object(
               'id', entry.id,
               'name', entry.display_name,
               'avatar', entry.avatar,
               'isBot', entry.is_bot,
               'isMe', (not entry.is_bot and entry.user_id = p_user_id),
               'bet', entry.stake,
               'chance', case
                 when v_round.total_pot > 0
                   then round(entry.stake::numeric * 100 / v_round.total_pot, 1)
                 else 0
               end,
               'payout', entry.payout
             )
        into v_winner
        from public.arena_entries as entry
       where entry.id = v_round.winner_entry_id;
    end if;
  end if;

  select coalesce(
           jsonb_agg(
             jsonb_build_object(
               'id', past.id,
               'totalPot', past.total_pot,
               'winnerName', winner.display_name,
               'winnerAvatar', winner.avatar,
               'winnerIsBot', winner.is_bot,
               'payout', past.payout,
               'finishedAt', past.finished_at
             )
             order by past.id desc
           ),
           '[]'::jsonb
         )
    into v_history
    from (
      select rounds.id, rounds.total_pot, rounds.winner_entry_id,
             rounds.payout, rounds.finished_at
        from public.arena_rounds as rounds
       where rounds.status = 'finished'
       order by rounds.id desc
       limit 5
    ) as past
    left join public.arena_entries as winner
      on winner.id = past.winner_entry_id;

  return jsonb_build_object(
    'available', true,
    'minBet', 1,
    'maxBet', 10000,
    'rakePercent', 10,
    'round', case
      when v_has_round then jsonb_build_object(
        'id', v_round.id,
        'status', v_round.status,
        'startedAt', v_round.created_at,
        'endsAt', v_round.closes_at,
        'finishedAt', v_round.finished_at,
        'totalPot', v_round.total_pot,
        'participantCount', jsonb_array_length(v_participants),
        'participants', v_participants,
        'myEntry', v_my_entry,
        'winner', v_winner,
        'payout', v_round.payout,
        'myResult', case
          when v_my_entry is null then null
          when v_round.status <> 'finished' then 'joined'
          when (v_my_entry ->> 'isWinner')::boolean then 'won'
          else 'lost'
        end
      )
      else null
    end,
    'history', v_history
  );
end;
$$;

create or replace function public.arena_join(
  p_user_id bigint,
  p_bet bigint,
  p_display_name text default 'Игрок'
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_round public.arena_rounds%rowtype;
  v_wallet public.wallet%rowtype;
  v_entry public.arena_entries%rowtype;
  v_participant_count integer;
  v_balance bigint;
  v_zt_balance bigint;
  v_users_state jsonb;
  v_user_state jsonb;
  v_user_key text := p_user_id::text;
  v_name text;
  v_avatar text;
  v_arena jsonb;
  v_has_round boolean;
  v_round_started_at timestamptz;
  v_round_duration_seconds integer;
begin
  if p_user_id is null or p_user_id <= 0 then
    raise exception 'Некорректный пользователь';
  end if;
  if p_bet is null or p_bet < 1 or p_bet > 10000 then
    raise exception 'Ставка должна быть от 1 до 10000 ZenoToken';
  end if;

  perform pg_advisory_xact_lock(816184092026);

  select *
    into v_round
    from public.arena_rounds
   where status = 'open'
   order by id desc
   limit 1
   for update;

  v_has_round := found;
  if v_has_round and v_round.closes_at <= clock_timestamp() then
    perform public.arena_resolve_round(v_round.id);
    v_has_round := false;
  end if;

  if not v_has_round then
    v_round_started_at := clock_timestamp();
    v_round_duration_seconds := 20 + floor(random() * 11)::integer;
    insert into public.arena_rounds (created_at, closes_at)
    values (
      v_round_started_at,
      v_round_started_at + make_interval(secs => v_round_duration_seconds)
    )
    returning * into v_round;
  end if;

  select *
    into v_entry
    from public.arena_entries
   where round_id = v_round.id
     and user_id = p_user_id
     and not is_bot
   for update;

  if not found then
    select count(*)
      into v_participant_count
      from public.arena_entries
     where round_id = v_round.id;
     if v_participant_count >= 8 then
      raise exception 'Слишком много участников в раунде';
    end if;
  end if;

  select state_value
    into v_users_state
    from public.bot_state
   where state_key = 'users'
   for update;

  if not found or v_users_state is null
     or jsonb_typeof(v_users_state) <> 'object' then
    raise exception 'Supabase bot_state row state_key=users was not found or is invalid';
  end if;

  v_user_state := coalesce(v_users_state -> v_user_key, '{}'::jsonb);
  if coalesce(v_user_state ->> 'zenotoken', '') ~ '^[0-9]+$' then
    v_zt_balance := (v_user_state ->> 'zenotoken')::bigint;
  else
    v_zt_balance := 0;
  end if;

  if v_zt_balance < p_bet then
    raise exception 'Недостаточно ZenoToken для этой ставки';
  end if;

  v_users_state := jsonb_set(
    v_users_state,
    array[v_user_key, 'zenotoken']::text[],
    to_jsonb(v_zt_balance - p_bet),
    true
  );
  update public.bot_state
     set state_value = v_users_state
   where state_key = 'users';

  insert into public.wallet (user_id, earn_balance, zeno_balance)
  values (p_user_id, 0, 0)
  on conflict (user_id) do nothing;

  select *
    into v_wallet
    from public.wallet
   where user_id = p_user_id
   for update;

  update public.wallet
     set zeno_balance = v_zt_balance - p_bet,
         updated_at = now()
   where user_id = p_user_id
   returning zeno_balance into v_balance;

  v_name := left(coalesce(nullif(trim(p_display_name), ''), 'Игрок'), 48);
  v_avatar := upper(left(v_name, 1));

  if v_entry.id is null then
    insert into public.arena_entries (
      round_id, user_id, display_name, avatar, is_bot, stake
    )
    values (
      v_round.id, p_user_id, v_name, v_avatar, false, p_bet
    )
    returning * into v_entry;
  else
    update public.arena_entries
       set stake = stake + p_bet,
           display_name = v_name,
           avatar = v_avatar
     where id = v_entry.id
     returning * into v_entry;
  end if;

  update public.arena_rounds
     set total_pot = total_pot + p_bet
   where id = v_round.id;

  v_arena := public.arena_get_state(p_user_id, v_name);

  return jsonb_build_object(
    'balance', v_balance,
    'zenoBalance', v_balance,
    'earnBalance', v_wallet.earn_balance,
    'arena', v_arena
  );
end;
$$;

revoke all on public.arena_rounds from anon, authenticated;
revoke all on public.arena_entries from anon, authenticated;
revoke all on public.arena_bot_profiles from anon, authenticated;
grant all on public.arena_rounds to service_role;
grant all on public.arena_entries to service_role;
grant all on public.arena_bot_profiles to service_role;

revoke all on function public.arena_resolve_round(bigint) from public, anon, authenticated;
revoke all on function public.arena_get_state(bigint, text) from public, anon, authenticated;
revoke all on function public.arena_join(bigint, bigint, text) from public, anon, authenticated;
grant execute on function public.arena_get_state(bigint, text) to service_role;
grant execute on function public.arena_join(bigint, bigint, text) to service_role;