-- Zeno Wallet storage.
-- Run this once in the Supabase SQL editor for the project used by Zeno.

create table if not exists public.wallet (
  user_id bigint primary key,
  earn_balance bigint not null default 0 check (earn_balance >= 0),
  zeno_balance bigint not null default 0 check (zeno_balance >= 0),
  updated_at timestamptz not null default now(),
  daily_claimed_at timestamptz,
  referred_by bigint,
  referral_rewarded boolean not null default false
);

alter table public.wallet
  add column if not exists daily_claimed_at timestamptz,
  add column if not exists referred_by bigint,
  add column if not exists referral_rewarded boolean not null default false;

create index if not exists wallet_updated_at_idx
  on public.wallet (updated_at desc);

-- Rocket crash game. Active rounds are kept in the database so a restart
-- cannot silently erase a user's in-flight bet.
create table if not exists public.games (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  game_name text not null,
  bet bigint not null check (bet > 0),
  multiplier numeric(10, 2),
  result text not null default 'active'
    check (result in ('active', 'won', 'lost')),
  created_at timestamptz not null default now(),
  started_at timestamptz not null default now(),
  crash_at numeric(10, 2) not null check (crash_at >= 1.2 and crash_at <= 500),
  payout bigint not null default 0 check (payout >= 0),
  settled_at timestamptz
);

alter table public.games
  add column if not exists started_at timestamptz not null default now(),
  add column if not exists crash_at numeric(10, 2),
  add column if not exists payout bigint not null default 0,
  add column if not exists settled_at timestamptz;

-- Roulette rows share this ledger but do not have a crash point.
alter table public.games
  alter column crash_at drop not null;

-- Upgrade the first crash-game migration from the old 1.5x–10x range.
alter table public.games drop constraint if exists games_crash_at_check;
alter table public.games drop constraint if exists games_crash_at_range_check;
do $$
begin
  if not exists (
    select 1
      from pg_constraint
     where conrelid = 'public.games'::regclass
       and conname = 'games_crash_at_range_check'
  ) then
    alter table public.games
      add constraint games_crash_at_range_check
      check (crash_at >= 1.2 and crash_at <= 500);
  end if;
end;
$$;

create index if not exists games_user_history_idx
  on public.games (user_id, game_name, created_at desc);

create unique index if not exists games_one_active_rocket_idx
  on public.games (user_id, game_name)
  where result = 'active' and game_name = 'rocket';

-- Roulette uses the same immutable game ledger as crash, with one daily
-- counter per user and one global jackpot lock per UTC day.
create table if not exists public.roulette_daily (
  user_id bigint not null,
  play_date date not null default current_date,
  free_plays_used integer not null default 0 check (free_plays_used >= 0),
  primary key (user_id, play_date)
);

create table if not exists public.roulette_jackpot_daily (
  play_date date primary key default current_date,
  claimed_at timestamptz,
  claimed_by bigint
);

-- The bot uses the REST API with the project key. Keep RLS disabled for this
-- server-side table, or add equivalent policies for the key used by the bot.
-- Never expose SUPABASE_KEY in a client-side application.

-- Seasonal competitions. These tables are intentionally separate from
-- bot_state so season data can be reset without touching bot settings/users.
create table if not exists public.seasons (
  id bigint generated by default as identity primary key,
  season_number bigint not null default 1,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  status text not null default 'active'
    check (status in ('active', 'finished')),
  finished_at timestamptz,
  announcement_sent_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.seasons
  add column if not exists season_number bigint;

update public.seasons
   set season_number = id
 where season_number is null;

alter table public.seasons
  alter column season_number set default 1,
  alter column season_number set not null;

create unique index if not exists seasons_one_active_idx
  on public.seasons (status)
  where status = 'active';

create table if not exists public.season_scores (
  season_id bigint not null references public.seasons(id) on delete cascade,
  user_id bigint not null,
  username text,
  display_name text not null default '',
  points bigint not null default 0 check (points >= 0),
  activity_count bigint not null default 0 check (activity_count >= 0),
  cases_opened bigint not null default 0 check (cases_opened >= 0),
  updated_at timestamptz not null default now(),
  primary key (season_id, user_id)
);

create index if not exists season_scores_leaderboard_idx
  on public.season_scores (season_id, points desc, updated_at asc, user_id asc);

create table if not exists public.season_rewards (
  season_id bigint not null references public.seasons(id) on delete cascade,
  user_id bigint not null,
  place integer not null check (place between 1 and 3),
  username text,
  display_name text not null default '',
  token_reward bigint not null default 0 check (token_reward >= 0),
  bonus_reward bigint not null default 0 check (bonus_reward >= 0),
  awarded_at timestamptz not null default now(),
  primary key (season_id, user_id),
  unique (season_id, place)
);

alter table public.season_rewards
  add column if not exists zeno_token_synced_at timestamptz;

create or replace function public.season_ensure_active()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_season public.seasons%rowtype;
begin
  select *
    into v_season
    from public.seasons
   where status = 'active'
   order by starts_at desc
   limit 1;

  if not found then
    insert into public.seasons (season_number, starts_at, ends_at)
    values (
      coalesce((select max(season_number) from public.seasons), 0) + 1,
      now(),
      now() + interval '3 days'
    )
    returning * into v_season;
  end if;

  return jsonb_build_object(
    'season_id', v_season.id,
    'starts_at', v_season.starts_at,
    'ends_at', v_season.ends_at,
    'status', v_season.status
  );
end;
$$;

create or replace function public.crash_multiplier_for(p_started_at timestamptz)
returns numeric
language plpgsql
volatile
set search_path = public
as $$
declare
  v_elapsed numeric;
begin
  v_elapsed := greatest(
    0,
    extract(epoch from (clock_timestamp() - p_started_at))
  );
  -- Matches the client animation: about 1.08x, 1.26x, 1.47x...
  -- at one-second intervals after the 3–2–1 pre-launch countdown.
  return round((1 + (0.07 * v_elapsed) + (0.025 * v_elapsed * v_elapsed))::numeric, 2);
end;
$$;

create or replace function public.crash_start(
  p_user_id bigint,
  p_bet bigint,
  p_crash_at numeric
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_wallet public.wallet%rowtype;
  v_game public.games%rowtype;
begin
  if p_bet is null or p_bet <= 0 then
    raise exception 'Ставка должна быть больше нуля';
  end if;
  if p_crash_at is null or p_crash_at < 1.2 or p_crash_at > 500 then
    raise exception 'Некорректная точка краша';
  end if;

  insert into public.wallet (user_id, earn_balance, zeno_balance)
  values (p_user_id, 0, 0)
  on conflict (user_id) do nothing;

  select *
    into v_wallet
    from public.wallet
   where user_id = p_user_id
   for update;

  if v_wallet.earn_balance < p_bet then
    raise exception 'Недостаточно монет для этой ставки';
  end if;

  update public.wallet
     set earn_balance = earn_balance - p_bet,
         updated_at = now()
   where user_id = p_user_id;

  insert into public.games (
    user_id, game_name, bet, result, crash_at
  )
  values (
    p_user_id, 'rocket', p_bet, 'active', round(p_crash_at, 2)
  )
  returning * into v_game;

  return jsonb_build_object(
    'gameId', v_game.id,
    'bet', v_game.bet,
    'startedAt', v_game.started_at,
    'crashAt', v_game.crash_at,
    'balance', v_wallet.earn_balance - p_bet
  );
end;
$$;

create or replace function public.crash_cashout(
  p_user_id bigint,
  p_game_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_game public.games%rowtype;
  v_wallet public.wallet%rowtype;
  v_live_multiplier numeric;
  v_payout bigint;
begin
  select *
    into v_game
    from public.games
   where id = p_game_id
     and user_id = p_user_id
     and game_name = 'rocket'
   for update;

  if not found then
    raise exception 'Раунд не найден';
  end if;
  if v_game.result <> 'active' then
    select *
      into v_wallet
      from public.wallet
     where user_id = p_user_id;
    return jsonb_build_object(
      'gameId', v_game.id,
      'result', v_game.result,
      'bet', v_game.bet,
      'multiplier', coalesce(v_game.multiplier, v_game.crash_at),
      'payout', v_game.payout,
      'balance', v_wallet.earn_balance
    );
  end if;

  v_live_multiplier := public.crash_multiplier_for(v_game.started_at);
  if v_live_multiplier >= v_game.crash_at then
    update public.games
       set result = 'lost',
           multiplier = v_game.crash_at,
           payout = 0,
           settled_at = now()
     where id = v_game.id;

    select *
      into v_wallet
      from public.wallet
     where user_id = p_user_id;

    return jsonb_build_object(
      'gameId', v_game.id,
      'result', 'lost',
      'bet', v_game.bet,
      'multiplier', v_game.crash_at,
      'payout', 0,
      'balance', v_wallet.earn_balance
    );
  end if;

  v_live_multiplier := least(v_live_multiplier, v_game.crash_at);
  v_payout := floor(v_game.bet * v_live_multiplier)::bigint;

  select *
    into v_wallet
    from public.wallet
   where user_id = p_user_id
   for update;

  update public.wallet
     set earn_balance = earn_balance + v_payout,
         updated_at = now()
   where user_id = p_user_id;

  update public.games
     set result = 'won',
         multiplier = v_live_multiplier,
         payout = v_payout,
         settled_at = now()
   where id = v_game.id;

  return jsonb_build_object(
    'gameId', v_game.id,
    'result', 'won',
    'bet', v_game.bet,
    'multiplier', v_live_multiplier,
    'payout', v_payout,
    'balance', v_wallet.earn_balance + v_payout
  );
end;
$$;

create or replace function public.crash_settle_loss(
  p_user_id bigint,
  p_game_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_game public.games%rowtype;
  v_wallet public.wallet%rowtype;
  v_live_multiplier numeric;
begin
  select *
    into v_game
    from public.games
   where id = p_game_id
     and user_id = p_user_id
     and game_name = 'rocket'
   for update;

  if not found then
    raise exception 'Раунд не найден';
  end if;
  if v_game.result <> 'active' then
    select *
      into v_wallet
      from public.wallet
     where user_id = p_user_id;
    return jsonb_build_object(
      'gameId', v_game.id,
      'result', v_game.result,
      'bet', v_game.bet,
      'multiplier', coalesce(v_game.multiplier, v_game.crash_at),
      'payout', v_game.payout,
      'balance', v_wallet.earn_balance
    );
  end if;

  v_live_multiplier := public.crash_multiplier_for(v_game.started_at);
  if v_live_multiplier < v_game.crash_at then
    raise exception 'Ракета ещё в полёте';
  end if;

  update public.games
     set result = 'lost',
         multiplier = v_game.crash_at,
         payout = 0,
         settled_at = now()
   where id = v_game.id;

  select *
    into v_wallet
    from public.wallet
   where user_id = p_user_id;

  return jsonb_build_object(
    'gameId', v_game.id,
    'result', 'lost',
    'bet', v_game.bet,
    'multiplier', v_game.crash_at,
    'payout', 0,
    'balance', v_wallet.earn_balance
  );
end;
$$;

-- Standard roulette probabilities are server-side and atomic. The 50x
-- jackpot is limited to one successful claim per UTC day.
create or replace function public.roulette_play(
  p_user_id bigint,
  p_bet bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_wallet public.wallet%rowtype;
  v_daily public.roulette_daily%rowtype;
  v_jackpot public.roulette_jackpot_daily%rowtype;
  v_users_state jsonb;
  v_user_key text;
  v_zeno_balance bigint;
  v_roll numeric;
  v_multiplier numeric := 0;
  v_result text := 'lost';
  v_payout bigint := 0;
  v_game_id bigint;
  v_paid_spin boolean := false;
  v_today date := current_date;
begin
  if p_bet is null or p_bet not in (10, 50, 100, 500) then
    raise exception 'Выбери ставку: 10, 50, 100 или 500 монет';
  end if;

  insert into public.wallet (user_id, earn_balance, zeno_balance)
  values (p_user_id, 0, 0)
  on conflict (user_id) do nothing;

  select *
    into v_wallet
    from public.wallet
   where user_id = p_user_id
   for update;

  select state_value
    into v_users_state
    from public.bot_state
   where state_key = 'users'
   for update;

  if not found or v_users_state is null
     or jsonb_typeof(v_users_state) <> 'object' then
    raise exception 'Supabase bot_state row state_key=users was not found or is invalid';
  end if;

  v_user_key := p_user_id::text;
  if coalesce(v_users_state -> v_user_key ->> 'zenotoken', '') ~ '^[0-9]+$' then
    v_zeno_balance := (v_users_state -> v_user_key ->> 'zenotoken')::bigint;
  else
    v_zeno_balance := 0;
  end if;

  if v_wallet.earn_balance < p_bet then
    raise exception 'Недостаточно монет для этой ставки';
  end if;

  insert into public.roulette_daily (user_id, play_date, free_plays_used)
  values (p_user_id, v_today, 0)
  on conflict (user_id, play_date) do nothing;

  select *
    into v_daily
    from public.roulette_daily
   where user_id = p_user_id
     and play_date = v_today
   for update;

  insert into public.roulette_jackpot_daily (play_date)
  values (v_today)
  on conflict (play_date) do nothing;

  select *
    into v_jackpot
    from public.roulette_jackpot_daily
   where play_date = v_today
   for update;

  if v_daily.free_plays_used >= 3 then
    if v_zeno_balance < 1 then
      raise exception 'Бесплатные прокруты закончились. Нужен 1 ZT';
    end if;
    v_paid_spin := true;
  end if;

  v_roll := random() * 100;
  if v_roll < 70 then
    v_multiplier := 0;
  elsif v_roll < 88 then
    v_multiplier := 2;
  elsif v_roll < 95 then
    v_multiplier := 3;
  elsif v_roll < 98 then
    v_multiplier := 5;
  elsif v_roll < 99.8 then
    v_multiplier := 10;
  elsif v_roll < 100 and v_jackpot.claimed_at is null then
    v_multiplier := 50;
    v_result := 'won';
    update public.roulette_jackpot_daily
       set claimed_at = now(), claimed_by = p_user_id
     where play_date = v_today;
  end if;

  if v_multiplier > 0 and v_result <> 'won' then
    v_result := 'won';
  end if;
  v_payout := floor(p_bet * v_multiplier)::bigint;

  if v_paid_spin then
    v_zeno_balance := v_zeno_balance - 1;
    v_users_state := jsonb_set(
      v_users_state,
      array[v_user_key, 'zenotoken']::text[],
      to_jsonb(v_zeno_balance),
      true
    );
    update public.bot_state
       set state_value = v_users_state
     where state_key = 'users';
  end if;

  update public.wallet
     set earn_balance = earn_balance - p_bet + v_payout,
         zeno_balance = v_zeno_balance,
         updated_at = now()
   where user_id = p_user_id
   returning * into v_wallet;

  if not v_paid_spin then
    update public.roulette_daily
       set free_plays_used = free_plays_used + 1
     where user_id = p_user_id
       and play_date = v_today
     returning * into v_daily;
  end if;

  insert into public.games (
    user_id, game_name, bet, multiplier, result, payout
  )
  values (
    p_user_id, 'roulette', p_bet, v_multiplier, v_result, v_payout
  )
  returning id into v_game_id;

  return jsonb_build_object(
    'gameId', v_game_id,
    'bet', p_bet,
    'result', v_result,
    'multiplier', v_multiplier,
    'payout', v_payout,
    'paidSpin', v_paid_spin,
    'ztCost', case when v_paid_spin then 1 else 0 end,
    'mode', 'standard',
    'balance', v_wallet.earn_balance,
    'zenoBalance', v_zeno_balance,
    'freeSpinsUsed', v_daily.free_plays_used,
    'freeSpinsRemaining', greatest(0, 3 - v_daily.free_plays_used)
  );
end;
$$;

grant execute on function public.roulette_play(bigint, bigint)
  to anon, authenticated, service_role;

-- Premium roulette is paid in ZenoToken instead of Telegram Stars. It keeps
-- the regular earn-balance bet, charges 100 ZT for the premium spin, and uses
-- a separate, still conservative multiplier table.
create or replace function public.roulette_play_premium(
  p_user_id bigint,
  p_bet bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_wallet public.wallet%rowtype;
  v_jackpot public.roulette_jackpot_daily%rowtype;
  v_premium_fee bigint := 100;
  v_roll numeric;
  v_multiplier numeric := 0;
  v_result text := 'lost';
  v_payout bigint := 0;
  v_game_id bigint;
  v_today date := current_date;
begin
  if p_bet is null or p_bet not in (10, 50, 100, 500) then
    raise exception 'Выбери ставку: 10, 50, 100 или 500 монет';
  end if;

  insert into public.wallet (user_id, earn_balance, zeno_balance)
  values (p_user_id, 0, 0)
  on conflict (user_id) do nothing;

  select *
    into v_wallet
    from public.wallet
   where user_id = p_user_id
   for update;

  if v_wallet.earn_balance < p_bet + v_premium_fee then
    raise exception 'Недостаточно монет для премиум-ставки';
  end if;

  insert into public.roulette_jackpot_daily (play_date)
  values (v_today)
  on conflict (play_date) do nothing;

  select *
    into v_jackpot
    from public.roulette_jackpot_daily
   where play_date = v_today
   for update;

  v_roll := random() * 100;
  if v_roll < 73 then
    v_multiplier := 0;
  elsif v_roll < 87 then
    v_multiplier := 2;
  elsif v_roll < 94 then
    v_multiplier := 3;
  elsif v_roll < 97 then
    v_multiplier := 5;
  elsif v_roll < 99 then
    v_multiplier := 10;
  elsif v_roll < 99.8 then
    v_multiplier := 20;
  elsif v_jackpot.claimed_at is null then
    v_multiplier := 50;
    v_result := 'won';
    update public.roulette_jackpot_daily
       set claimed_at = now(), claimed_by = p_user_id
     where play_date = v_today;
  end if;

  if v_multiplier > 0 and v_result <> 'won' then
    v_result := 'won';
  end if;
  v_payout := floor(p_bet * v_multiplier)::bigint;

  update public.wallet
     set earn_balance = earn_balance - p_bet - v_premium_fee + v_payout,
         updated_at = now()
   where user_id = p_user_id
   returning * into v_wallet;

  insert into public.games (
    user_id, game_name, bet, multiplier, result, payout
  )
  values (
    p_user_id, 'roulette_premium', p_bet, v_multiplier, v_result, v_payout
  )
  returning id into v_game_id;

  return jsonb_build_object(
    'gameId', v_game_id,
    'bet', p_bet,
    'result', v_result,
    'multiplier', v_multiplier,
    'payout', v_payout,
    'paidSpin', true,
    'ztCost', 0,
    'premiumFee', v_premium_fee,
    'mode', 'premium',
    'balance', v_wallet.earn_balance,
    'zenoBalance', v_wallet.zeno_balance
  );
end;
$$;

grant execute on function public.roulette_play_premium(bigint, bigint)
  to anon, authenticated, service_role;

-- Remove ZenoToken awarded by older season versions. Season rewards belong
-- only in the main wallet balance, so this migration reverses the old
-- duplicate credit once and clears the old token ledger value.
do $$
declare
  v_users_state jsonb;
  v_reward record;
  v_current_zeno bigint;
begin
  select state_value
    into v_users_state
    from public.bot_state
   where state_key = 'users'
   for update;

  if not found or v_users_state is null or jsonb_typeof(v_users_state) <> 'object' then
    raise exception 'Supabase bot_state row state_key=users was not found or is invalid';
  end if;

  for v_reward in
    select season_id, user_id, token_reward
      from public.season_rewards
     where token_reward > 0
     order by awarded_at, season_id, place
  loop
    if coalesce(v_users_state -> v_reward.user_id::text ->> 'zenotoken', '') ~ '^[0-9]+$' then
      v_current_zeno := (v_users_state -> v_reward.user_id::text ->> 'zenotoken')::bigint;
    else
      v_current_zeno := 0;
    end if;

    v_users_state := jsonb_set(
      v_users_state,
      array[v_reward.user_id::text],
      coalesce(v_users_state -> v_reward.user_id::text, '{}'::jsonb)
        || jsonb_build_object(
          'zenotoken',
          greatest(v_current_zeno - v_reward.token_reward, 0)
        ),
      true
    );

    update public.wallet
       set zeno_balance = greatest(zeno_balance - v_reward.token_reward, 0),
           updated_at = now()
     where user_id = v_reward.user_id;

    update public.season_rewards
       set token_reward = 0,
           zeno_token_synced_at = null
     where season_id = v_reward.season_id
       and user_id = v_reward.user_id;
  end loop;

  update public.bot_state
     set state_value = v_users_state
   where state_key = 'users';
end;
$$;

create or replace function public.season_set_number(p_season_number bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_season public.seasons%rowtype;
begin
  if p_season_number is null or p_season_number < 1 then
    raise exception 'Season number must be a positive integer';
  end if;

  update public.seasons
     set season_number = p_season_number
   where status = 'active'
   returning * into v_season;

  if not found then
    raise exception 'Active season was not found';
  end if;

  return jsonb_build_object(
    'season_id', v_season.id,
    'season_number', v_season.season_number,
    'starts_at', v_season.starts_at,
    'ends_at', v_season.ends_at
  );
end;
$$;

-- Creates the first season on demand and atomically adds points to a user.
create or replace function public.season_add_points(
  p_user_id bigint,
  p_username text default null,
  p_display_name text default '',
  p_activity_points integer default 0,
  p_case_points integer default 0
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_season public.seasons%rowtype;
  v_total integer := greatest(coalesce(p_activity_points, 0), 0)
    + greatest(coalesce(p_case_points, 0), 0);
begin
  select *
    into v_season
    from public.seasons
   where status = 'active'
   order by starts_at desc
   limit 1
   for update;

  if not found then
    insert into public.seasons (season_number, starts_at, ends_at)
    values (
      coalesce((select max(season_number) from public.seasons), 0) + 1,
      now(),
      now() + interval '3 days'
    )
    returning * into v_season;
  end if;

  if v_season.ends_at <= now() then
    return jsonb_build_object(
      'expired', true,
      'season_id', v_season.id
    );
  end if;

  insert into public.season_scores (
    season_id, user_id, username, display_name, points,
    activity_count, cases_opened, updated_at
  )
  values (
    v_season.id, p_user_id, nullif(p_username, ''),
    coalesce(nullif(p_display_name, ''), 'ID ' || p_user_id),
    v_total, greatest(coalesce(p_activity_points, 0), 0),
    case when coalesce(p_case_points, 0) > 0 then 1 else 0 end, now()
  )
  on conflict (season_id, user_id) do update set
    username = coalesce(excluded.username, season_scores.username),
    display_name = case
      when excluded.display_name <> '' then excluded.display_name
      else season_scores.display_name
    end,
    points = season_scores.points + excluded.points,
    activity_count = season_scores.activity_count + excluded.activity_count,
    cases_opened = season_scores.cases_opened + excluded.cases_opened,
    updated_at = now();

  return jsonb_build_object(
    'expired', false,
    'season_id', v_season.id,
    'points_added', v_total
  );
end;
$$;

-- Finishes one expired season, pays the top 3, and opens the next one.
-- The row lock plus unique reward keys makes repeated maintenance calls safe.
drop function if exists public.season_finalize_expired();

create or replace function public.season_finalize_expired(p_force boolean default false)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_season public.seasons%rowtype;
  v_new_season public.seasons%rowtype;
  v_score record;
  v_place integer := 0;
  v_token bigint;
  v_bonus bigint;
  v_winners jsonb := '[]'::jsonb;
begin
  select *
    into v_season
    from public.seasons
   where status = 'active'
     and (p_force or ends_at <= now())
   order by ends_at
   limit 1
   for update skip locked;

  if not found then
    return jsonb_build_object('finalized', false);
  end if;

  for v_score in
    select user_id, username, display_name, points
      from public.season_scores
     where season_id = v_season.id
     order by points desc, updated_at asc, user_id asc
     limit 3
  loop
    v_place := v_place + 1;
    v_token := 0;
    v_bonus := case
      when v_place = 1 then 100
      when v_place = 2 then 75
      when v_place = 3 then 50
      else 0
    end;

    insert into public.season_rewards (
      season_id, user_id, place, username, display_name,
      token_reward, bonus_reward
    )
    values (
      v_season.id, v_score.user_id, v_place, v_score.username,
      coalesce(v_score.display_name, 'ID ' || v_score.user_id),
      v_token, v_bonus
    )
    on conflict (season_id, user_id) do nothing;

    if found then
      insert into public.wallet (user_id, earn_balance, zeno_balance)
      values (v_score.user_id, 0, 0)
      on conflict (user_id) do nothing;

      update public.wallet
         set earn_balance = earn_balance + v_bonus,
             updated_at = now()
       where user_id = v_score.user_id;
    end if;

    v_winners := v_winners || jsonb_build_object(
      'place', v_place,
      'user_id', v_score.user_id,
      'username', v_score.username,
      'display_name', coalesce(v_score.display_name, 'ID ' || v_score.user_id),
      'points', v_score.points,
      'token_reward', v_token,
      'bonus_reward', v_bonus
    );
  end loop;

  update public.seasons
     set status = 'finished', finished_at = now()
   where id = v_season.id;

  insert into public.seasons (season_number, starts_at, ends_at)
  values (
    v_season.season_number + 1,
    now(),
    now() + interval '3 days'
  )
  returning * into v_new_season;

  return jsonb_build_object(
    'finalized', true,
    'season_id', v_season.id,
    'season_number', v_season.season_number,
    'starts_at', v_season.starts_at,
    'ends_at', v_season.ends_at,
    'winners', v_winners,
    'new_season_id', v_new_season.id
  );
end;
$$;