-- Zeno Wallet storage.
-- Run this once in the Supabase SQL editor for the project used by Zeno.

create table if not exists public.wallet (
  user_id bigint primary key,
  earn_balance bigint not null default 0 check (earn_balance >= 0),
  zeno_balance bigint not null default 0 check (zeno_balance >= 0),
  updated_at timestamptz not null default now(),
  daily_claimed_at timestamptz,
  referred_by bigint,
  referral_rewarded boolean not null default false
);

alter table public.wallet
  add column if not exists daily_claimed_at timestamptz,
  add column if not exists referred_by bigint,
  add column if not exists referral_rewarded boolean not null default false;

create index if not exists wallet_updated_at_idx
  on public.wallet (updated_at desc);

-- The bot uses the REST API with the project key. Keep RLS disabled for this
-- server-side table, or add equivalent policies for the key used by the bot.
-- Never expose SUPABASE_KEY in a client-side application.

-- Seasonal competitions. These tables are intentionally separate from
-- bot_state so season data can be reset without touching bot settings/users.
create table if not exists public.seasons (
  id bigint generated by default as identity primary key,
  season_number bigint not null default 1,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  status text not null default 'active'
    check (status in ('active', 'finished')),
  finished_at timestamptz,
  announcement_sent_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.seasons
  add column if not exists season_number bigint;

update public.seasons
   set season_number = id
 where season_number is null;

alter table public.seasons
  alter column season_number set default 1,
  alter column season_number set not null;

create unique index if not exists seasons_one_active_idx
  on public.seasons (status)
  where status = 'active';

create table if not exists public.season_scores (
  season_id bigint not null references public.seasons(id) on delete cascade,
  user_id bigint not null,
  username text,
  display_name text not null default '',
  points bigint not null default 0 check (points >= 0),
  activity_count bigint not null default 0 check (activity_count >= 0),
  cases_opened bigint not null default 0 check (cases_opened >= 0),
  updated_at timestamptz not null default now(),
  primary key (season_id, user_id)
);

create index if not exists season_scores_leaderboard_idx
  on public.season_scores (season_id, points desc, updated_at asc, user_id asc);

create table if not exists public.season_rewards (
  season_id bigint not null references public.seasons(id) on delete cascade,
  user_id bigint not null,
  place integer not null check (place between 1 and 3),
  username text,
  display_name text not null default '',
  token_reward bigint not null default 0 check (token_reward >= 0),
  bonus_reward bigint not null default 0 check (bonus_reward >= 0),
  awarded_at timestamptz not null default now(),
  primary key (season_id, user_id),
  unique (season_id, place)
);

alter table public.season_rewards
  add column if not exists zeno_token_synced_at timestamptz;

create or replace function public.season_ensure_active()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_season public.seasons%rowtype;
begin
  select *
    into v_season
    from public.seasons
   where status = 'active'
   order by starts_at desc
   limit 1;

  if not found then
    insert into public.seasons (season_number, starts_at, ends_at)
    values (
      coalesce((select max(season_number) from public.seasons), 0) + 1,
      now(),
      now() + interval '3 days'
    )
    returning * into v_season;
  end if;

  return jsonb_build_object(
    'season_id', v_season.id,
    'starts_at', v_season.starts_at,
    'ends_at', v_season.ends_at,
    'status', v_season.status
  );
end;
$$;

-- Move rewards created by older versions from wallet-only storage into the
-- Zeno bot's canonical bot_state balance. The marker makes this idempotent.
do $$
declare
  v_users_state jsonb;
  v_reward record;
  v_current_zeno bigint;
begin
  select state_value
    into v_users_state
    from public.bot_state
   where state_key = 'users'
   for update;

  if found and v_users_state is not null and jsonb_typeof(v_users_state) = 'object' then
    for v_reward in
      select season_id, user_id, token_reward
        from public.season_rewards
       where zeno_token_synced_at is null
       order by awarded_at, season_id, place
    loop
      if coalesce(v_users_state -> v_reward.user_id::text ->> 'zenotoken', '') ~ '^[0-9]+$' then
        v_current_zeno := (v_users_state -> v_reward.user_id::text ->> 'zenotoken')::bigint;
      else
        v_current_zeno := 0;
      end if;

      v_users_state := jsonb_set(
        v_users_state,
        array[v_reward.user_id::text],
        coalesce(v_users_state -> v_reward.user_id::text, '{}'::jsonb)
          || jsonb_build_object(
            'zenotoken',
            v_current_zeno + v_reward.token_reward
          ),
        true
      );

      update public.season_rewards
         set zeno_token_synced_at = now()
       where season_id = v_reward.season_id
         and user_id = v_reward.user_id;
    end loop;

    update public.bot_state
       set state_value = v_users_state
     where state_key = 'users';
  end if;
end;
$$;

create or replace function public.season_set_number(p_season_number bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_season public.seasons%rowtype;
begin
  if p_season_number is null or p_season_number < 1 then
    raise exception 'Season number must be a positive integer';
  end if;

  update public.seasons
     set season_number = p_season_number
   where status = 'active'
   returning * into v_season;

  if not found then
    raise exception 'Active season was not found';
  end if;

  return jsonb_build_object(
    'season_id', v_season.id,
    'season_number', v_season.season_number,
    'starts_at', v_season.starts_at,
    'ends_at', v_season.ends_at
  );
end;
$$;

-- Creates the first season on demand and atomically adds points to a user.
create or replace function public.season_add_points(
  p_user_id bigint,
  p_username text default null,
  p_display_name text default '',
  p_activity_points integer default 0,
  p_case_points integer default 0
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_season public.seasons%rowtype;
  v_total integer := greatest(coalesce(p_activity_points, 0), 0)
    + greatest(coalesce(p_case_points, 0), 0);
begin
  select *
    into v_season
    from public.seasons
   where status = 'active'
   order by starts_at desc
   limit 1
   for update;

  if not found then
    insert into public.seasons (season_number, starts_at, ends_at)
    values (
      coalesce((select max(season_number) from public.seasons), 0) + 1,
      now(),
      now() + interval '3 days'
    )
    returning * into v_season;
  end if;

  if v_season.ends_at <= now() then
    return jsonb_build_object(
      'expired', true,
      'season_id', v_season.id
    );
  end if;

  insert into public.season_scores (
    season_id, user_id, username, display_name, points,
    activity_count, cases_opened, updated_at
  )
  values (
    v_season.id, p_user_id, nullif(p_username, ''),
    coalesce(nullif(p_display_name, ''), 'ID ' || p_user_id),
    v_total, greatest(coalesce(p_activity_points, 0), 0),
    case when coalesce(p_case_points, 0) > 0 then 1 else 0 end, now()
  )
  on conflict (season_id, user_id) do update set
    username = coalesce(excluded.username, season_scores.username),
    display_name = case
      when excluded.display_name <> '' then excluded.display_name
      else season_scores.display_name
    end,
    points = season_scores.points + excluded.points,
    activity_count = season_scores.activity_count + excluded.activity_count,
    cases_opened = season_scores.cases_opened + excluded.cases_opened,
    updated_at = now();

  return jsonb_build_object(
    'expired', false,
    'season_id', v_season.id,
    'points_added', v_total
  );
end;
$$;

-- Finishes one expired season, pays the top 3, and opens the next one.
-- The row lock plus unique reward keys makes repeated maintenance calls safe.
drop function if exists public.season_finalize_expired();

create or replace function public.season_finalize_expired(p_force boolean default false)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_season public.seasons%rowtype;
  v_new_season public.seasons%rowtype;
  v_score record;
  v_place integer := 0;
  v_token bigint;
  v_bonus bigint;
  v_winners jsonb := '[]'::jsonb;
  v_users_state jsonb;
  v_current_zeno bigint;
begin
  select *
    into v_season
    from public.seasons
   where status = 'active'
     and (p_force or ends_at <= now())
   order by ends_at
   limit 1
   for update skip locked;

  if not found then
    return jsonb_build_object('finalized', false);
  end if;

  select state_value
    into v_users_state
    from public.bot_state
   where state_key = 'users'
   for update;

  if not found or v_users_state is null or jsonb_typeof(v_users_state) <> 'object' then
    raise exception 'Supabase bot_state row state_key=users was not found or is invalid';
  end if;

  for v_score in
    select user_id, username, display_name, points
      from public.season_scores
     where season_id = v_season.id
     order by points desc, updated_at asc, user_id asc
     limit 3
  loop
    v_place := v_place + 1;
    v_token := case
      when v_place = 1 then 100
      when v_place = 2 then 75
      when v_place = 3 then 50
      else 0
    end;
    v_bonus := v_token;

    insert into public.season_rewards (
      season_id, user_id, place, username, display_name,
      token_reward, bonus_reward
    )
    values (
      v_season.id, v_score.user_id, v_place, v_score.username,
      coalesce(v_score.display_name, 'ID ' || v_score.user_id),
      v_token, v_bonus
    )
    on conflict (season_id, user_id) do nothing;

    if found then
      insert into public.wallet (user_id, earn_balance, zeno_balance)
      values (v_score.user_id, 0, 0)
      on conflict (user_id) do nothing;

      update public.wallet
         set earn_balance = earn_balance + v_bonus,
             zeno_balance = zeno_balance + v_token,
             updated_at = now()
       where user_id = v_score.user_id;

      if coalesce(v_users_state -> v_score.user_id::text ->> 'zenotoken', '') ~ '^[0-9]+$' then
        v_current_zeno := (v_users_state -> v_score.user_id::text ->> 'zenotoken')::bigint;
      else
        v_current_zeno := 0;
      end if;

      v_users_state := jsonb_set(
        v_users_state,
        array[v_score.user_id::text],
        coalesce(v_users_state -> v_score.user_id::text, '{}'::jsonb)
          || jsonb_build_object('zenotoken', v_current_zeno + v_token),
        true
      );

      update public.season_rewards
         set zeno_token_synced_at = now()
       where season_id = v_season.id
         and user_id = v_score.user_id;
    end if;

    v_winners := v_winners || jsonb_build_object(
      'place', v_place,
      'user_id', v_score.user_id,
      'username', v_score.username,
      'display_name', coalesce(v_score.display_name, 'ID ' || v_score.user_id),
      'points', v_score.points,
      'token_reward', v_token,
      'bonus_reward', v_bonus
    );
  end loop;

  update public.bot_state
     set state_value = v_users_state
   where state_key = 'users';

  update public.seasons
     set status = 'finished', finished_at = now()
   where id = v_season.id;

  insert into public.seasons (season_number, starts_at, ends_at)
  values (
    v_season.season_number + 1,
    now(),
    now() + interval '3 days'
  )
  returning * into v_new_season;

  return jsonb_build_object(
    'finalized', true,
    'season_id', v_season.id,
    'season_number', v_season.season_number,
    'starts_at', v_season.starts_at,
    'ends_at', v_season.ends_at,
    'winners', v_winners,
    'new_season_id', v_new_season.id
  );
end;
$$;